import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml",
]

live_config_reload = true

[font]
normal = { family = "Roboto Mono Nerd Font Mono", style = "Regular" }
size = 10

[cursor]
style = { shape = "Beam", blinking = "Off" }

[window]
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"
