[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml",
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

[cursor]
style = { shape = "Beam", blinking = "Off" }

[window]
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[selection]
save_to_clipboard = true
